bagging_fraction: 0.2
bagging_freq: 1
boosting: dart
colsample_bytree: 1.0
device_type: cpu
drop_rate: 0.375
extra_trees: false
feature_fraction: 0.5
feature_fraction_bynode: 0.4
lambda_l1: 0
lambda_l2: 100
learning_rate: 0.2
max_depth: 7
min_child_weight: 0.00071
min_data_in_leaf: 90
min_gain_to_split: 0.09899999999999999
n_estimators: 110
num_leaves: 20
pos_bagging_fraction: 0.6000000000000001
