bagging_fraction: 0.5
bagging_freq: 11
boosting: dart
colsample_bytree: 1.3
device_type: cpu
drop_rate: 0.43000000000000005
extra_trees: false
feature_fraction: 0.4
feature_fraction_bynode: 0.55
lambda_l1: 50
lambda_l2: 70
learning_rate: 0.08
max_depth: 4
min_child_weight: 0.00021
min_data_in_leaf: 90
min_gain_to_split: 0.075
n_estimators: 180
num_leaves: 30
pos_bagging_fraction: 0.5
