bagging_fraction: 0.30000000000000004
bagging_freq: 1
boosting: dart
colsample_bytree: 1.2
device_type: cpu
feature_fraction: 0.9
lambda_l1: 5
lambda_l2: 0
learning_rate: 0.18000000000000002
max_bin: 237
max_depth: 7
min_child_weight: 1.0e-05
min_data_in_leaf: 80
min_gain_to_split: 2.030808318976094
n_estimators: 120
num_leaves: 15
